// Generated by CoffeeScript 1.2.1-pre

window.onload = function() {
  var actors, c, makeWall, r, wh, world, ww, x, _i;
  ww = wh = Math.min(window.innerWidth, window.innerHeight);
  actors = [];
  world = new World(ww, wh, 30, 0, 9);
  makeWall = function() {
    var bh, bw, wall, wallBd, wallLeft, wallRight, _wallBottom, _wallTop;
    wall = new _PolygonShape();
    wallBd = new _BodyDef();
    bw = ww / 30;
    bh = wh / 30;
    wallBd.position.Set(.25, 0);
    wall.SetAsBox(.25, bh);
    wallLeft = world.world.CreateBody(wallBd);
    wallLeft.CreateFixture2(wall);
    wallBd.position.Set(bw - .25, 0);
    wallRight = world.world.CreateBody(wallBd);
    wallRight.CreateFixture2(wall);
    wallBd.position.Set(0, .25);
    wall.SetAsBox(bw, .25);
    _wallTop = world.world.CreateBody(wallBd);
    _wallTop.CreateFixture2(wall);
    wallBd.position.Set(0, bh - .25);
    _wallBottom = world.world.CreateBody(wallBd);
    return _wallBottom.CreateFixture2(wall);
  };
  window.onkeydown = function(e) {
    if (e.keyCode === 68) {
      world.debug = !world.debug;
      if (!world.debug) return world.debugLayer.clear();
    } else {
      return world.boxLayer.draw();
    }
  };
  makeWall();
  for (x = _i = 0; _i <= 8; x = ++_i) {
    r = new Rect(world, {
      x: x * 10,
      y: 50 + 3 * x,
      w: x + 1,
      h: x + 1,
      a: x + 1,
      fill: '#ddd'
    });
  }
  c = new Circle(world, {
    x: 4,
    y: 20,
    r: 2,
    fill: '#eee'
  });
  return world.render();
};
